INFO 04-26 17:54:26 [__init__.py:239] Automatically detected platform cuda.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/stud/wxie/EasyR1/verl/trainer/main.py", line 147, in <module>
    main()
  File "/home/stud/wxie/EasyR1/verl/trainer/main.py", line 116, in main
    ppo_config = OmegaConf.merge(default_config, cli_args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wiss/liao/miniconda3/envs/easyr1/lib/python3.11/site-packages/omegaconf/omegaconf.py", line 273, in merge
    target.merge_with(*configs[1:])
  File "/home/wiss/liao/miniconda3/envs/easyr1/lib/python3.11/site-packages/omegaconf/basecontainer.py", line 492, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/home/wiss/liao/miniconda3/envs/easyr1/lib/python3.11/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/wiss/liao/miniconda3/envs/easyr1/lib/python3.11/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/home/wiss/liao/miniconda3/envs/easyr1/lib/python3.11/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wiss/liao/miniconda3/envs/easyr1/lib/python3.11/site-packages/omegaconf/basecontainer.py", line 490, in merge_with
    self._merge_with(*others)
  File "/home/wiss/liao/miniconda3/envs/easyr1/lib/python3.11/site-packages/omegaconf/basecontainer.py", line 514, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/wiss/liao/miniconda3/envs/easyr1/lib/python3.11/site-packages/omegaconf/basecontainer.py", line 399, in _map_merge
    dest_node._merge_with(src_node)
  File "/home/wiss/liao/miniconda3/envs/easyr1/lib/python3.11/site-packages/omegaconf/basecontainer.py", line 514, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/home/wiss/liao/miniconda3/envs/easyr1/lib/python3.11/site-packages/omegaconf/basecontainer.py", line 423, in _map_merge
    dest._format_and_raise(key=key, value=src_value, cause=e)
  File "/home/wiss/liao/miniconda3/envs/easyr1/lib/python3.11/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/wiss/liao/miniconda3/envs/easyr1/lib/python3.11/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/wiss/liao/miniconda3/envs/easyr1/lib/python3.11/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wiss/liao/miniconda3/envs/easyr1/lib/python3.11/site-packages/omegaconf/basecontainer.py", line 420, in _map_merge
    dest_node._set_value(src_value)
  File "/home/wiss/liao/miniconda3/envs/easyr1/lib/python3.11/site-packages/omegaconf/nodes.py", line 46, in _set_value
    self._val = self.validate_and_convert(value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wiss/liao/miniconda3/envs/easyr1/lib/python3.11/site-packages/omegaconf/nodes.py", line 66, in validate_and_convert
    raise ValidationError(
omegaconf.errors.ValidationError: Incompatible value 'None' for field of type 'str'
    full_key: data.train_files
    reference_type=DataConfig
    object_type=DataConfig
